### ISSUE TITLE
faille login connexion octogone

### ISSUE THREAD

**Issue by 14roiron** [UDEEMP/Portail-Des-Eleves#10]
> La clé devrait se trouver dans le fichier settings global et donc pas sur github, car à partir de ca, je peux changer les soldes de n'importe qui sur le portail (mais pas dans la base octo donc c'est pas critique)
> je peux changer la clé de l'octogone si tu veux
>  @16pierre

```

AAahhh mmerrrddeeee, j'avais pas tilté du tout que la variable était configuré sur la version online, ça marchait pas chez moi donc j'ai corrigé sans trop réfléchir...

C'est vrai que ça pose des vrais problèmes de sécurité via le git, j'avais pas tilté...

Tu as accès au code octo roiron?

Je laisse le code comme ça jusqu'à demain sur le FTP pour voir ce que ça donne.
Malheureusement sur le FTP j'ai plus accès à l'ancien views.py du dossier trombi, cependant je vois pas de SECRET_KEY_UPDATE dans le settings principal sur le FTP, et je ne l'ai pas actualisé. Donc soit l'ancien views.py du FTP était pas à jour avec le GIT et utilisait autre chose que SECRET_KEY_UPDATE, et dans ce cas il était possible qu'il soit fonctionnel et que ça soit l'octogone qui bug, soit il manquait le secret_key_update tout court...

Dans tous les cas, on saura demain à midi très rapidement, puisque là c'est pas le portail qui bug ;)


```
https://github.com/UDEEMP/Portail-Des-Eleves/commit/09f6ecb675b40f028c677314511e15f46ec61f6a

on va continuer ici c'est plus claire @16pierre 

oui j'ai accès au code et je peux même déclencher un envoie si besoin.

possible que ce soit l'octogone je regarde tout à l'heure mais avec ce fix, tu t'attends à ce que ça marche c'est ça? 
il faudrait que l'on mette en place des tests pour débug ça.

après on pourra changer les clés si besoin de toutes façons, mais à l'avenir on les mets dans le settings?

**Comment by 14roiron** [comment]
tu avais modifié les sous domaines @16pierre  @FlorianVeaux  ?
le pb etait que le script de l'octo se connectait à http://eleves.mines-paris.eu/ et pas http://www.eleves.mines-paris.eu/ normalement c'est bon

**Comment by 14roiron** [comment]
@16pierre  on peut donc changer la clé si tu veux


les logs d'upload sont ici si besoin:
http://octogone/upload.log

**Comment by 16pierre** [comment]
OK niquel, merci pour le lien

D'après le log tu as effectué la modif pour que ça marche Roiron nan?
Je pense tout de même que mon ajout de clé était nécessaire puisque je trouvais pas la variable ailleurs

Oui à l'avenir je propose qu'on le mette dans le settings global (on parle bien du settings dans le sous-dossier portail ?)
Tu voudrais qu'on ne publie pas la clé sur github mais uniquement sur le ftp ?

**Comment by 14roiron** [comment]
yep, je te laisse verifier si besoin,

yep pour le fichier
